### PR TITLE
fix possible memory leak at 6.5+

### PR DESCRIPTION
**Pull request by bbaa-bbaa**
Porting the missing section on [0b62af2](https://github.com/gregkh/linux/commit/0b62af28f249b9c4036a05acfb053058dc02e2e2)

May fix: #137
May fix: #175

### CODE REVIEW

**Comment by Nightmare41241** [comment]
Excuse me but how to use it.

**Comment by bbaa-bbaa** [comment]
> Excuse me but how to use it.

You can refer to [README.md](https://github.com/strongtz/i915-sriov-dkms/blob/master/README.md), but please replace all git clone with my branch `git clone https://github.com/bbaa-bbaa/i915-sriov-dkms`.

**Comment by Nightmare41241** [comment]
螢幕快照 2024-10-03 01-25-24
螢幕快照 2024-10-03 01-24-32
it still not work

**Comment by Nightmare41241** [comment]
i not using any high ram usage application

**Comment by bbaa-bbaa** [comment]
> i not using any high ram usage application

Which kernel version are you using?

**Comment by vit0sd** [comment]
No leak in arch 6.11.1 after replacing drivers/gpu/drm/i915/gem/i915_gem_shmem.c by i915_gem_shmem.c from 6.11.1-arch1-1

**Comment by bbaa-bbaa** [comment]
> No leak in arch 6.11.1 after replacing drivers/gpu/drm/i915/gem/i915_gem_shmem.c by i915_gem_shmem.c from 6.11.1-arch1-1

Thanks, I will keep only the fix of i915_gem_shmem.c in this PR.

**Comment by strongtz** [comment]
Merged,  thanks!

**Comment by Nightmare41241** [comment]
> > i not using any high ram usage application
> 
> Which kernel version/OS are you using?

sorry for late reply, i am using 6.6 xanmod v3. idk may the problem of xanmod?

**Pull request merged**
