### PR TITLE
i915 module: build with linux-6.4.5

### PR DESCRIPTION
**Pull request by PisonJay**
#97. `drm_dp_mst_hpd_irq()` broken due to [this commit](https://github.com/torvalds/linux/commit/104d79eb58aa63330e9cbcb5095177c234b9c859)

### CODE REVIEW

**Comment by odror** [comment]
Any updates regarding kernel 6.4

**Comment by sempervictus** [comment]
It seems to build, but the way they shim the gen8 and gen12 encoding calls creates a CFI violation (at least w/ RAP, likely kCFI as well - haven't tested that yet).

**Comment by sempervictus** [comment]
6.1.47 seems to need this as well - appears they backported the change.

**Comment by chenzaichun** [comment]
6.1.49 need this patch as well.

**Comment by sempervictus** [comment]
Eh, actually I think it's 47 but I did this work on the 6.4 branch before I pulled it back to my 6.1 and realized the same. Can make another PR shortly

**Pull request merged**
