### PR TITLE
Correction for PR #178

### PR DESCRIPTION
**Pull request by pasbec**
Hi @strongtz,

Shame on me - i had a small typo `DEFINE_EXTRAVERSION` vs `EXTRAVERSION_DEFINE` in the Makefile of my last PR due to some last minute changes.
This fixes PR #178 and adds some option to overwrite the default GuC firmware if necessary.

Sorry for the inconveniences. Should have made a last test before opening the last PR.

### CODE REVIEW

**Comment by IanRanson** [comment]
Was getting build errors with main branch, but can confirm this PR works well.  Thanks so much for your great work!

**Comment by ich777** [comment]
I just wanted to point out that it won't compile because of a few errors.
With this PR everything compiles just fine and I've already built a package for the Unraid community to test.

**Comment by pasbec** [comment]
Thank you @IanRanson and @ich777 . I tried to sneak that fix into the last PR but it was simlply merged to quickly. 🫣

**Comment by ich777** [comment]
I'm sure @strongtz will merge it ASAP. :)

**Comment by johntdavis84** [comment]
Will the merge include updates to the README/front page to refresh to list of compatible kernels on the host and inside the VM?

-- -- --
John T Davis
***@***.***

**Comment by pasbec** [comment]
> Will the merge include updates to the README/front page to refresh to list of compatible kernels on the host and inside the VM?

I've only done some brief update of the README.md in PR #178 but there is no change in #179. I have only quickly listed (added) the Proxmox kernels that I tested. Without testing other distros and differnt kernels (e.g. Proxmox has no 6.6 or 6.7)  it is quite hard to tell which kernels are actually working.

**Comment by ich777** [comment]
@pasbec working fine on Unraid:
grafik

**Pull request merged**
