### PR TITLE
Change the upstream to the mainline-tracking linux/6.12 branch.

### PR DESCRIPTION
**Pull request by bbaa-bbaa**
Change the upstream to the [mainline-tracking](https://github.com/intel/mainline-tracking/tree/linux/v6.12) linux/6.12 branch.

Test on kernel  6.13.0-rc4-1-mainline/6.12.6-zen1/6.11.9-arch1/6.10.9-arch1/6.9.10-arch1/6.8.9-arch1 with ArchLinux

Supported kernel version: 6.8 ~ 6.13

### CODE REVIEW

**Comment by johntdavis84** [comment]
Hello!

Hope you're having a great holiday season. :)
How does this PR relate to the ongoing rebase to the 6.6 kernel? Are you skipping 6.6 and going straight to 6.12 (now that it's LTS?)?

**Comment by strongtz** [comment]
Thanks for your work! I wonder if this is supposed to be merged at some point?

**Comment by bbaa-bbaa** [comment]
> How does this PR relate to the ongoing rebase to the 6.6 kernel? Are you skipping 6.6 and going straight to 6.12?

The PR based on the 6.6 branch has some unresolved upstream issues, so I chose to switch to the latest branch to receive fix patches from upstream.

The  code has been backported, with the minimum supported version being Linux 6.8 (which is the default kernel used by Ubuntu 24.04/Proxmox VE 8.3).

> now that it's LTS?

Yes, Linux 6.12 is the new LTS kernel (https://www.kernel.org/category/releases.html), so we may occasionally pick patches from the linux-stable.git tree.

**Comment by bbaa-bbaa** [comment]
> Thanks for your work! I wonder if this is supposed to be merged at some point?

I think this PR is able to merge, but we may need to create a new branch to preserve the code supporting versions 6.1-6.11, and add guidance in the README pointing to the original branch.

**Comment by bbaa-bbaa** [comment]
@strongtz Do you think we need to create a branch to preserve the previous code based on Linux 6.1, or  just to add a note in the README with previous commit id references?

**Comment by strongtz** [comment]
I have created a branch to preserve the old code. :p

**Pull request merged**
