### PR TITLE
More fixed for NULL pointer dereference error in wa_list_apply

### PR DESCRIPTION
**Pull request by zhtengw**
Tested on PVE Host 6.2.9-1-pve 6.2.11-1-pve, Gentoo guest 6.1.19-gentoo, Fedora 37 guest 6.2.13-200.fc37.x86_64.

### CODE REVIEW

**Comment by zhtengw** [comment]
@sieske Please help to test this commit if it is fix the issue.

**Comment by zhtengw** [comment]
@sieskei Please help to test this commit if it is fix the issue.

**Comment by sieskei** [comment]
No problem, in about 30 min I will be on the computer and test again.

**Comment by sieskei** [comment]
This time, boot.
No kernel crash after create one VF.

```
[   79.619067] pci 0000:00:02.1: [8086:9a60] type 00 class 0x030000
[   79.619119] pci 0000:00:02.1: DMAR: Skip IOMMU disabling for graphics
[   79.619242] pci 0000:00:02.1: Adding to iommu group 22
[   79.619252] pci 0000:00:02.1: vgaarb: bridge control possible
[   79.619254] pci 0000:00:02.1: vgaarb: VGA device added: decodes=io+mem,owns=none,locks=none
[   79.619261] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=none:owns=io+mem
[   79.619267] vfio-pci 0000:04:00.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=none:owns=none
[   79.619453] i915 0000:00:02.1: enabling device (0000 -> 0002)
[   79.619495] i915 0000:00:02.1: Running in SR-IOV VF mode
[   79.619839] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.0.0
[   79.620415] i915 0000:00:02.1: [drm] VT-d active for gfx access
[   79.620503] i915 0000:00:02.1: [drm] Using Transparent Hugepages
[   79.621480] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.0.0
[   79.621785] i915 0000:00:02.1: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[   79.621793] i915 0000:00:02.1: HuC firmware PRELOADED
[   79.625395] i915 0000:00:02.1: [drm] Protected Xe Path (PXP) protected content support initialized
[   79.625400] i915 0000:00:02.1: [drm] PMU not supported for this GPU.
[   79.625619] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.1 on minor 1
[   79.625792] i915 0000:00:02.0: Enabled 1 VFs
**[   80.643052] i915 0000:00:02.1: [drm] *ERROR* tlb invalidation response timed out for seqno 23**
[   80.683565] vfio-pci 0000:00:02.1: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=none
```

**Comment by zhtengw** [comment]
Tested work on Ubuntu 22.04.2 LTS (GNU/Linux 6.1.0-1009-oem x86_64)
```
test-ubuntu:~$ uname -a
Linux test-ubuntu 6.1.0-1009-oem #9-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 09:59:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
test-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
test-ubuntu:~$ sudo dmesg | grep i915
[sudo] password for aten:
[    1.271276] i915: loading out-of-tree module taints kernel.
[    1.272335] i915: module verification failed: signature and/or required key missing - tainting kernel
[    1.390209] i915 0000:00:10.0: Running in SR-IOV VF mode
[    1.390597] i915 0000:00:10.0: [drm] GT0: GUC: interface version 0.1.0.0
[    1.391095] i915 0000:00:10.0: [drm] VT-d active for gfx access
[    1.391291] i915 0000:00:10.0: [drm] Using Transparent Hugepages
[    1.392095] i915 0000:00:10.0: [drm] GT0: GUC: interface version 0.1.0.0
[    1.392445] i915 0000:00:10.0: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[    1.392612] i915 0000:00:10.0: HuC firmware PRELOADED
[    1.393982] i915 0000:00:10.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    1.394151] i915 0000:00:10.0: [drm] PMU not supported for this GPU.
[    1.394409] [drm] Initialized i915 1.6.0 20201103 for 0000:00:10.0 on minor 1
```

**Comment by sieskei** [comment]
**Guest**

Linux m16-vm-ubuntu 6.3.1-x64v3-xanmod1 #0~20230503.cf0c658 SMP PREEMPT_DYNAMIC Wed May  3 07:36:18 UTC  x86_64 x86_64 x86_64 GNU/Linux

```
[    2.696049] i915 0000:05:00.0: Running in SR-IOV VF mode
[    2.696682] i915 0000:05:00.0: [drm] GT0: GUC: interface version 0.1.0.0
[    2.697733] i915 0000:05:00.0: [drm] Using Transparent Hugepages
[    2.701502] i915 0000:05:00.0: [drm] GT0: GUC: interface version 0.1.0.0
[    2.701716] i915 0000:05:00.0: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[    2.701718] i915 0000:05:00.0: HuC firmware PRELOADED
[    2.703622] i915 0000:05:00.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    2.703629] i915 0000:05:00.0: [drm] PMU not supported for this GPU.
[    2.703694] [drm] Initialized i915 1.6.0 20201103 for 0000:05:00.0 on minor 1
```

**Pull request merged**
